CREATE TABLE IF NOT EXISTS "ApplicationUsers" (
  "Id" uuid NOT NULL,
  "UserName" character varying(50) NOT NULL,
  "Email" character varying(100) NOT NULL,
  "Password" text NOT NULL,
  "Role" character varying(50) NULL,
  "Token" text NULL,
  "RefreshToken" text NULL,
  "RefreshTokenExpiryTime" timestamp with time zone NOT NULL,
  "LastLoginTime" timestamp with time zone NOT NULL,
  "IsOnline" boolean NOT NULL,
  "CreatedAt" timestamp with time zone NOT NULL,
  "UpdatedAt" timestamp with time zone NOT NULL,
  "DeletedAt" timestamp with time zone NOT NULL,
  "IsDeleted" boolean NOT NULL,
  CONSTRAINT "PK_ApplicationUsers" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS "Tickets" (
  "TicketId" uuid NOT NULL,
  "SubmitterId" uuid NOT NULL,
  "AssigneeId" uuid NULL,
  "Environment" integer NOT NULL,
  "Title" text NOT NULL,
  "Description" text NOT NULL,
  "StepsToReproduce" text NOT NULL,
  "ExpectedResult" text NOT NULL,
  "IsResolved" boolean NOT NULL,
  "CreatedAt" timestamp with time zone NOT NULL,
  "UpdatedAt" timestamp with time zone NOT NULL,
  "DeletedAt" timestamp with time zone NOT NULL,
  "IsDeleted" boolean NOT NULL,
  CONSTRAINT "PK_Tickets" PRIMARY KEY ("TicketId"),
  CONSTRAINT "FK_Tickets_ApplicationUsers_AssigneeId" FOREIGN KEY ("AssigneeId") REFERENCES "ApplicationUsers" ("Id") ON DELETE RESTRICT,
  CONSTRAINT "FK_Tickets_ApplicationUsers_SubmitterId" FOREIGN KEY ("SubmitterId") REFERENCES "ApplicationUsers" ("Id") ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS "IX_Tickets_AssigneeId" ON "Tickets" ("AssigneeId");
CREATE INDEX IF NOT EXISTS "IX_Tickets_SubmitterId" ON "Tickets" ("SubmitterId");

CREATE TABLE IF NOT EXISTS "TicketFiles" (
  "Id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "TicketId" uuid NOT NULL,
  "Content" bytea NOT NULL,
  "CreatedAt" timestamp with time zone NOT NULL,
  "UpdatedAt" timestamp with time zone NOT NULL,
  "DeletedAt" timestamp with time zone NOT NULL,
  "IsDeleted" boolean NOT NULL,
  CONSTRAINT "PK_TicketFiles" PRIMARY KEY ("Id"),
  CONSTRAINT "FK_TicketFiles_Tickets_TicketId" FOREIGN KEY ("TicketId") REFERENCES "Tickets" ("TicketId") ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS "IX_TicketFiles_TicketId" ON "TicketFiles" ("TicketId");

