-- Human-friendly ticket number, while keeping UUID for integrity/lookups.
ALTER TABLE "Tickets" ADD COLUMN IF NOT EXISTS "TicketNumber" bigint;

CREATE SEQUENCE IF NOT EXISTS "Tickets_TicketNumber_seq" AS bigint;
ALTER TABLE "Tickets" ALTER COLUMN "TicketNumber" SET DEFAULT nextval('"Tickets_TicketNumber_seq"');

-- Backfill existing rows (stable order).
WITH ordered AS (
  SELECT "TicketId"
  FROM "Tickets"
  WHERE "TicketNumber" IS NULL
  ORDER BY "CreatedAt" ASC
)
UPDATE "Tickets" t
SET "TicketNumber" = nextval('"Tickets_TicketNumber_seq"')
FROM ordered o
WHERE t."TicketId" = o."TicketId";

ALTER TABLE "Tickets" ALTER COLUMN "TicketNumber" SET NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS "UX_Tickets_TicketNumber" ON "Tickets" ("TicketNumber");

-- Ticket messages (persisted chat/comments).
CREATE TABLE IF NOT EXISTS "TicketMessages" (
  "MessageId" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "TicketId" uuid NOT NULL,
  "SenderId" uuid NOT NULL,
  "Body" text NOT NULL,
  "CreatedAt" timestamp with time zone NOT NULL,
  CONSTRAINT "PK_TicketMessages" PRIMARY KEY ("MessageId"),
  CONSTRAINT "FK_TicketMessages_Tickets_TicketId" FOREIGN KEY ("TicketId") REFERENCES "Tickets" ("TicketId") ON DELETE CASCADE,
  CONSTRAINT "FK_TicketMessages_ApplicationUsers_SenderId" FOREIGN KEY ("SenderId") REFERENCES "ApplicationUsers" ("Id") ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS "IX_TicketMessages_TicketId_CreatedAt" ON "TicketMessages" ("TicketId", "CreatedAt");

